version: '3'

services:
  apollo-os:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - USE_MOCK_DB=true
    command: npm run dev:mock 